### PR TITLE
Added blog entry about pgspecial.

### PR DESCRIPTION
**Pull request by j-bennet**

### CODE REVIEW

**Comment by amjith** [comment]
Nice!

Can you add some examples in the blogpost? 

Some example of meta commands such as `\d [table]` as well as an example of how to use pgspecial via the python repl. Such as 

```
$ pip install pgspecial

$ python
>>> import pgspecial
>>> pgspecial.PGSpecial()
... 
etc
```

**Comment by j-bennet** [comment]
Sure.

**Comment by j-bennet** [comment]
@amjith How's that?

**Comment by amjith** [comment]
Looks great. Thanks for the nice blog post. :ice_cream:

**Pull request merged**
